#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use sdleiw\CoinMarketCap\Commands\SaveHistoryDataForCoinCommand;

$app = new Application();
$app->add(new SaveHistoryDataForCoinCommand);

$app->run();

